# Generated by Django 4.2.5 on 2023-11-19 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=30, verbose_name='Customer Name')),
                ('address', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=20)),
                ('amount_to_be_paid', models.CharField(max_length=20, verbose_name='Amount to be Paid')),
            ],
        ),
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('B', 'Bunglow'), ('A', 'Apartment')], max_length=2)),
                ('bedroom', models.CharField(max_length=20)),
                ('toilet', models.CharField(max_length=10)),
                ('size', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('statu', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=30)),
                ('sub_county', models.CharField(max_length=30)),
                ('block', models.IntegerField()),
                ('plot', models.IntegerField()),
                ('acrage', models.CharField(max_length=30)),
                ('title_photo', models.ImageField(default='', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(verbose_name='Payment Date')),
                ('amt_pd', models.CharField(max_length=20, verbose_name='Amount Paid')),
                ('rec_by', models.CharField(max_length=20, verbose_name='Received By')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestate.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('statu', models.CharField(max_length=30)),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestate.estate')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestate.house'),
        ),
        migrations.AddField(
            model_name='customer',
            name='land',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestate.land'),
        ),
    ]
